### ISSUE TITLE
Jupyter kernel error in AIND-Constraint_Satisfaction.ipynb

### ISSUE THREAD

**Issue by puhach** [udacity/artificial-intelligence#27]
Having created Miniconda environment from aind-universal-v3.yml, I am getting the following error when trying to open the AIND-Constraint_Satisfaction.ipynb notebook:
```
jupyter kernel ImportError: No module named 'win32api'
```

It looks like the environment file is missing the pywin32 extension.

**Comment by ronny-udacity** [comment]
`pywin32` needs to be installed in the local Windows machine. Please refer to this Stackoverflow [discussion](https://stackoverflow.com/questions/21343774/importerror-no-module-named-win32api).
