### ISSUE TITLE
README in planning search references wrong test script

### ISSUE THREAD

**Issue by MariaRigaki** [udacity/artificial-intelligence#3]
The README file instructions for Part 2 mention that in order to test the code one should execute `python -m unittest tests.test_my_pddl` while it should be `python -m unittest tests.test_my_air_cargo_problems`

**Comment by danainschool** [comment]
The instructions are correct.  The idea is to take the solution determined in part 2 and use those solutions as a verification that the PDDL and solution are in sync. It's probably not very clear though, so I have added some clarification.  This also brings up a good point though - the README doesn't mention the other tests for my_air_cargo_problems.  Instructions to run those have been added.
